"""initial schema

Revision ID: 49f2b70d631e
Revises: 
Create Date: 2026-07-13 10:02:48.474930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49f2b70d631e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registration',
    sa.Column('username', sa.String(length=32), nullable=True),
    sa.Column('first_name', sa.String(length=32), nullable=True),
    sa.Column('last_name', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('password_is_confirmed', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('email_is_confirmed', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('email_code_sent', sa.String(length=6), nullable=True),
    sa.Column('email_code_id', sa.String(length=32), nullable=True),
    sa.Column('email_code_expire_at', sa.DateTime(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('session', sa.String(length=256), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='True', nullable=False),
    sa.Column('is_locked', sa.Boolean(), server_default='False', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_registration_id'), 'registration', ['id'], unique=False)
    op.create_index(op.f('ix_registration_ip_address'), 'registration', ['ip_address'], unique=False)
    op.create_index(op.f('ix_registration_session'), 'registration', ['session'], unique=False)
    op.create_table('user',
    sa.Column('username', sa.String(length=32), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'VIEWER', name='userrole'), nullable=False),
    sa.Column('first_name', sa.String(length=32), nullable=False),
    sa.Column('last_name', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('email_confirmed', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('email_code_limit', sa.Integer(), nullable=False),
    sa.Column('bad_email_code_time', sa.DateTime(), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('password_change', sa.DateTime(), nullable=True),
    sa.Column('bad_password_count', sa.Integer(), nullable=False),
    sa.Column('bad_password_time', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='True', nullable=False),
    sa.Column('is_locked', sa.Boolean(), server_default='False', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_first_name'), 'user', ['first_name'], unique=False)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_index(op.f('ix_user_last_name'), 'user', ['last_name'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('login',
    sa.Column('login_method', sa.String(length=16), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('password_is_validated', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('email_matched', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('email_is_confirmed', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('email_code_sent', sa.String(length=6), nullable=True),
    sa.Column('email_code_id', sa.String(length=32), nullable=True),
    sa.Column('email_code_expire_at', sa.DateTime(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('session', sa.String(length=256), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='True', nullable=False),
    sa.Column('is_locked', sa.Boolean(), server_default='False', nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_login_id'), 'login', ['id'], unique=False)
    op.create_index(op.f('ix_login_ip_address'), 'login', ['ip_address'], unique=False)
    op.create_index(op.f('ix_login_session'), 'login', ['session'], unique=False)
    op.create_index(op.f('ix_login_user_id'), 'login', ['user_id'], unique=False)
    op.create_table('main',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('session', sa.String(length=256), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='True', nullable=False),
    sa.Column('is_locked', sa.Boolean(), server_default='False', nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_main_id'), 'main', ['id'], unique=False)
    op.create_index(op.f('ix_main_ip_address'), 'main', ['ip_address'], unique=False)
    op.create_index(op.f('ix_main_session'), 'main', ['session'], unique=False)
    op.create_index(op.f('ix_main_user_id'), 'main', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_main_user_id'), table_name='main')
    op.drop_index(op.f('ix_main_session'), table_name='main')
    op.drop_index(op.f('ix_main_ip_address'), table_name='main')
    op.drop_index(op.f('ix_main_id'), table_name='main')
    op.drop_table('main')
    op.drop_index(op.f('ix_login_user_id'), table_name='login')
    op.drop_index(op.f('ix_login_session'), table_name='login')
    op.drop_index(op.f('ix_login_ip_address'), table_name='login')
    op.drop_index(op.f('ix_login_id'), table_name='login')
    op.drop_table('login')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_last_name'), table_name='user')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_first_name'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_registration_session'), table_name='registration')
    op.drop_index(op.f('ix_registration_ip_address'), table_name='registration')
    op.drop_index(op.f('ix_registration_id'), table_name='registration')
    op.drop_table('registration')
    # ### end Alembic commands ###
