"""add ondelete for nodes

Revision ID: 73086c789320
Revises: e14a005debb0
Create Date: 2026-07-21 10:50:57.504217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73086c789320'
down_revision: Union[str, Sequence[str], None] = 'e14a005debb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('nodes_parent_id_fkey'), 'nodes', type_='foreignkey')
    op.create_foreign_key(None, 'nodes', 'nodes', ['parent_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'nodes', type_='foreignkey')
    op.create_foreign_key(op.f('nodes_parent_id_fkey'), 'nodes', 'nodes', ['parent_id'], ['id'])
    # ### end Alembic commands ###
