"""editor_session_drop_auth_fields_add_unique_index

Revision ID: 8e95442e5406
Revises: c5233aa7555a
Create Date: 2026-07-24 10:28:54.228982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e95442e5406'
down_revision: Union[str, Sequence[str], None] = 'c5233aa7555a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_editor_session_ip_address'), table_name='editor_session')
    op.drop_index(op.f('ix_editor_session_session'), table_name='editor_session')
    op.create_index('uq_active_session_per_node', 'editor_session', ['node_id'], unique=True, postgresql_where=sa.text('is_completed IS false'))
    op.drop_column('editor_session', 'ip_address')
    op.drop_column('editor_session', 'session')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('editor_session', sa.Column('session', sa.VARCHAR(length=256), autoincrement=False, nullable=False))
    op.add_column('editor_session', sa.Column('ip_address', sa.VARCHAR(length=45), autoincrement=False, nullable=True))
    op.drop_index('uq_active_session_per_node', table_name='editor_session', postgresql_where=sa.text('is_completed IS false'))
    op.create_index(op.f('ix_editor_session_session'), 'editor_session', ['session'], unique=False)
    op.create_index(op.f('ix_editor_session_ip_address'), 'editor_session', ['ip_address'], unique=False)
    # ### end Alembic commands ###
