"""editor_session

Revision ID: c5233aa7555a
Revises: 0e5541fde22e
Create Date: 2026-07-23 17:14:32.447010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c5233aa7555a'
down_revision: Union[str, Sequence[str], None] = '0e5541fde22e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('editor_session',
    sa.Column('node_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('draft_content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_discarded', sa.Boolean(), server_default='False', nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('last_autosaved_at', sa.DateTime(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('session', sa.String(length=256), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='True', nullable=False),
    sa.Column('is_locked', sa.Boolean(), server_default='False', nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_editor_session_id'), 'editor_session', ['id'], unique=False)
    op.create_index(op.f('ix_editor_session_ip_address'), 'editor_session', ['ip_address'], unique=False)
    op.create_index(op.f('ix_editor_session_node_id'), 'editor_session', ['node_id'], unique=False)
    op.create_index(op.f('ix_editor_session_session'), 'editor_session', ['session'], unique=False)
    op.create_index(op.f('ix_editor_session_user_id'), 'editor_session', ['user_id'], unique=False)
    op.drop_index(op.f('ix_redact_session_id'), table_name='redact_session')
    op.drop_index(op.f('ix_redact_session_ip_address'), table_name='redact_session')
    op.drop_index(op.f('ix_redact_session_node_id'), table_name='redact_session')
    op.drop_index(op.f('ix_redact_session_session'), table_name='redact_session')
    op.drop_index(op.f('ix_redact_session_user_id'), table_name='redact_session')
    op.drop_table('redact_session')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('redact_session',
    sa.Column('node_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('draft_content', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('is_discarded', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('is_completed', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('last_autosaved_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('session', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('is_locked', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.id'], name=op.f('redact_session_node_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('redact_session_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('redact_session_pkey'))
    )
    op.create_index(op.f('ix_redact_session_user_id'), 'redact_session', ['user_id'], unique=False)
    op.create_index(op.f('ix_redact_session_session'), 'redact_session', ['session'], unique=False)
    op.create_index(op.f('ix_redact_session_node_id'), 'redact_session', ['node_id'], unique=False)
    op.create_index(op.f('ix_redact_session_ip_address'), 'redact_session', ['ip_address'], unique=False)
    op.create_index(op.f('ix_redact_session_id'), 'redact_session', ['id'], unique=False)
    op.drop_index(op.f('ix_editor_session_user_id'), table_name='editor_session')
    op.drop_index(op.f('ix_editor_session_session'), table_name='editor_session')
    op.drop_index(op.f('ix_editor_session_node_id'), table_name='editor_session')
    op.drop_index(op.f('ix_editor_session_ip_address'), table_name='editor_session')
    op.drop_index(op.f('ix_editor_session_id'), table_name='editor_session')
    op.drop_table('editor_session')
    # ### end Alembic commands ###
