"""wiki models

Revision ID: e14a005debb0
Revises: 49f2b70d631e
Create Date: 2026-07-17 12:03:31.758247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e14a005debb0'
down_revision: Union[str, Sequence[str], None] = '49f2b70d631e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nodes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('type', sa.Enum('PAGE', 'SECTION', 'FOLDER', 'FILE', name='nodetype'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nodes_slug'), 'nodes', ['slug'], unique=False)
    op.create_index(op.f('ix_nodes_type'), 'nodes', ['type'], unique=False)
    op.create_table('file_contents',
    sa.Column('node_id', sa.Uuid(), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('node_id')
    )
    op.create_table('redact_session',
    sa.Column('node_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('draft_content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_discarded', sa.Boolean(), server_default='False', nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('last_autosaved_at', sa.DateTime(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('session', sa.String(length=256), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='True', nullable=False),
    sa.Column('is_locked', sa.Boolean(), server_default='False', nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_redact_session_id'), 'redact_session', ['id'], unique=False)
    op.create_index(op.f('ix_redact_session_ip_address'), 'redact_session', ['ip_address'], unique=False)
    op.create_index(op.f('ix_redact_session_node_id'), 'redact_session', ['node_id'], unique=False)
    op.create_index(op.f('ix_redact_session_session'), 'redact_session', ['session'], unique=False)
    op.create_index(op.f('ix_redact_session_user_id'), 'redact_session', ['user_id'], unique=False)
    op.create_index('uq_active_session_per_node', 'redact_session', ['node_id'], unique=True, postgresql_where=sa.text('is_completed IS false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_active_session_per_node', table_name='redact_session', postgresql_where=sa.text('is_completed IS false'))
    op.drop_index(op.f('ix_redact_session_user_id'), table_name='redact_session')
    op.drop_index(op.f('ix_redact_session_session'), table_name='redact_session')
    op.drop_index(op.f('ix_redact_session_node_id'), table_name='redact_session')
    op.drop_index(op.f('ix_redact_session_ip_address'), table_name='redact_session')
    op.drop_index(op.f('ix_redact_session_id'), table_name='redact_session')
    op.drop_table('redact_session')
    op.drop_table('file_contents')
    op.drop_index(op.f('ix_nodes_type'), table_name='nodes')
    op.drop_index(op.f('ix_nodes_slug'), table_name='nodes')
    op.drop_table('nodes')
    # ### end Alembic commands ###
